name: "Jupyter Notebook server"
description: "Installs and runs Jupyter Notebook server for debugging purpose"
author: "Gerard Braad <me@gbraad.nl>"

inputs:
  hangaround:
    description: 'Run the hangaround step'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install notebook
      id: setup
      shell: bash
      run: |
        pip install notebook
    - name: Run notebook server
      id: run
      shell: bash
      run: |
        jupyter notebook --ip 0.0.0.0 --no-browser --IdentityProvider.token='' &

    - name: Hang around
      if: ${{ inputs.hangaround == 'true' }}
      shell: bash
      run: |
        sleep infinity
